services:
  db:
    image: pgvector/pgvector:pg16
    container_name: ai4biz_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  admin:
    image: dpage/pgadmin4
    container_name: ai4biz_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - db

  cache:
    image: redis
    container_name: ai4biz_cache
    ports:
      - "6379:6379"
